// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2P909gLFaqB20-UlpOpSlJ8M1K65-41A',
    appId: '1:745348785939:web:a9eb25a2f898bab0f21ce6',
    messagingSenderId: '745348785939',
    projectId: 'lesson72',
    authDomain: 'lesson72.firebaseapp.com',
    storageBucket: 'lesson72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOd6jfjQ35Px5bE61eRdP-BLWfxUSQoVs',
    appId: '1:745348785939:android:023d045688613c2df21ce6',
    messagingSenderId: '745348785939',
    projectId: 'lesson72',
    storageBucket: 'lesson72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg1quV4jQQny_QHewlj6rRNTuQNwJ6Lao',
    appId: '1:745348785939:ios:da8227196c8ab5cef21ce6',
    messagingSenderId: '745348785939',
    projectId: 'lesson72',
    storageBucket: 'lesson72.appspot.com',
    iosBundleId: 'com.example.lesson72',
  );
}
